version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web/
    overwrite: purge
file_exists_behavior: OVERWRITE
hooks:
# stop service
  ApplicationStop:
    - location: codedeploy/stop_server.sh 
      timeout: 300
# clean images & volume before build an run new services
  AfterInstall:
    - location: codedeploy/docker_cleanup.sh
      timeout: 300
# start service
  ApplicationStart:
    - location: codedeploy/start_server.sh
      runas: root
      timeout: 300

