version: "3.3"
services:
  nginx:
    container_name: nginx-custom
    image: nginx-push-ecr:latest
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
      - ./log:/var/log/nginx/
    networks:
      - web-net

  php:
    container_name: php
    image: php-push-ecr:latest
    build:
      context: .
      dockerfile: ./Dockerfile.php
    volumes:
      - ./src:/var/www/html/
    working_dir: /var/www/html/
    networks:
      - web-net
networks:
  web-net:
    driver: bridge
